### ISSUE TITLE
Why Does He Look So Sad? 😩

### ISSUE THREAD

**Issue by zicklag** [Eudritch/clean-tauri-sveltekit#1]
https://github.com/Eudritch/clean-tauri-sveltekit/blob/3f24c2856461e7292943e5620c6bb353e06e3814/README.md?plain=1#L1

It just seemed a little counter-intuitive, almost like Tauri + Svelte doesn't work so well or something. :)

**Comment by Eudritch** [comment]
> https://github.com/Eudritch/clean-tauri-sveltekit/blob/3f24c2856461e7292943e5620c6bb353e06e3814/README.md?plain=1#L1
> 
> It just seemed a little counter-intuitive, almost like Tauri + Svelte doesn't work so well or something. :)

Tauri's backend is built with rust. I think it's better to keep these two folders separate, but I see what you mean. I'll look into improving the template and making tauri use icons from svelte src/static by default. I'll get back to you once it's finished.

**Comment by Eudritch** [comment]
It's what it is bro, AI found out he is not a real boy

**Comment by Eudritch** [comment]
😂
